In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder  
data = pd.read_csv('insurance.csv')
print(data)

      age     sex     bmi  children smoker     region     expenses
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder  
data = pd.read_csv('insurance.csv')
x=data.iloc[:,:6]
print(x)

      age     sex     bmi  children smoker     region
0      19  female  27.900         0    yes  southwest
1      18    male  33.770         1     no  southeast
2      28    male  33.000         3     no  southeast
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
...   ...     ...     ...       ...    ...        ...
1333   50    male  30.970         3     no  northwest
1334   18  female  31.920         0     no  northeast
1335   18  female  36.850         0     no  southeast
1336   21  female  25.800         0     no  southwest
1337   61  female  29.070         0    yes  northwest

[1338 rows x 6 columns]

In [17]:
import numpy as np  
import pandas as pd  
from sklearn.model_selection import train_test_split  
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score 
data = pd.read_csv('insurance.csv') 
X = data.iloc[:, :6] 
y= data.iloc[:, 1] 
le = LabelEncoder() 
categorical_columns = ['sex', 'smoker', 'region']   
for col in categorical_columns: 
    X[col] = le.fit_transform(X[col]) 
y = le.fit_transform(y) 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42) 
k=3 
knn = KNeighborsClassifier(n_neighbors=k) 
knn.fit(X_train,y_train) 
y_pred = knn.predict(X_test) 
sample=[[1,10,9,11,4,2]] 
k=knn.predict(sample) 
print(k) 
accuracy = accuracy_score(y_test,y_pred) 
print(accuracy)

[1]
0.6977611940298507

In [19]:
import pandas as pd 
from sklearn.model_selection import train_test_split  
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import LabelEncoder 
data = pd.read_csv('cricket.csv') 
X = data.iloc[:, :5] 
y= data.iloc[:, 4] 
le = LabelEncoder() 
categorical_columns = ['Outlook','Temp','Humidity','Windy','Play Cricket']   
for col in categorical_columns: 
    X[col] = le.fit_transform(X[col]) 
y = le.fit_transform(y) 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42) 
k=3 
knn = KNeighborsClassifier(n_neighbors=k) 
knn.fit(X_train,y_train) 
y_pred = knn.predict(X_test) 
sample=[[1,10,9,11,4]] 
k=knn.predict(sample) 
print(k) 
accuracy = accuracy_score(y_test,y_pred) 
print(accuracy)

[1]
1.0

In [21]:
import numpy as np  
import pandas as pd 
from sklearn.model_selection import train_test_split  
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import LabelEncoder 
data = pd.read_csv('food.csv') 
X = data.iloc[:, :3] 
y= data.iloc[:, 3] 
le = LabelEncoder() 
categorical_columns = ['Ingredient']   
for col in categorical_columns: 
    X[col] = le.fit_transform(X[col]) 
y = le.fit_transform(y) 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42) 
k=3 
knn = KNeighborsClassifier(n_neighbors=k) 
knn.fit(X_train,y_train) 
y_pred = knn.predict(X_test) 
sample=[[1,10,9]] 
k=knn.predict(sample) 
print(k) 
accuracy = accuracy_score(y_test,y_pred) 
print(accuracy)

[2]
0.3333333333333333

In [23]:
import pandas as pd
data=pd.read_csv('food.csv')
data

    Ingredient  Sweetness  Crunchiness   FoodType
0        apple         10            9      fruit
1        bacon          1            4    protein
2       banana         10            1      fruit
3       carrot          7           10  vegetable
4       celery          3           10  vegetable
5       cheese          1            1    protein
6     cucumber          2            8  vegetable
7         fish          3            1    protein
8        grape          8            5      fruit
9   green bean          3            7  vegetable
10     lettuce          1            9  vegetable
11        nuts          3            6    protein
12      orange          7            3      fruit
13        pear         10            7      fruit
14      shrimp          2            3    protein

In [24]:
import pandas as pd
data=pd.read_csv('insurance.csv')
data

      age     sex     bmi  children smoker     region     expenses
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
import pandas as pd
data=pd.read_csv('cricket.csv')
data

     Outlook  Temp Humidity Windy Play Cricket
0      Rainy   Hot     High    No           No
1      Rainy   Hot     High   Yes           No
2   Overcast   Hot     High    No          Yes
3      Sunny  Mild     High    No          Yes
4      Sunny  Cool   Normal    No          Yes
5      Sunny  Cool   Normal   Yes           No
6   Overcast  Cool   Normal   Yes          Yes
7      Rainy  Mild     High    No           No
8      Rainy  Cool   Normal    No          Yes
9      Sunny  Mild   Normal    No          Yes
10     Rainy  Mild   Normal   Yes          Yes
11  Overcast  Mild     High   Yes          Yes
12  Overcast   Hot   Normal    No          Yes
13     Sunny  Mild     High   Yes           No

In [2]:
import numpy as np
from sklearn import datasets,metrics
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
iris=datasets.load_iris()
X=iris.data
y=iris.target
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
nb_classifier=GaussianNB()
nb_classifier.fit(X_train,y_train)
y_pred=nb_classifier.predict(X_test)
accuracy=accuracy_score(y_test,y_pred) 
print(accuracy) 
print(f"Accuracy: {accuracy*100:.2f}%")

1.0
Accuracy: 100.00%

In [6]:
import pandas as pd
from sklearn import datasets,metrics
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
data = pd.read_csv('cricket.csv') 
X = data.iloc[:, :5] 
y= data.iloc[:, 4] 
le = LabelEncoder() 
categorical_columns = ['Outlook','Temp','Humidity','Windy','Play Cricket']   
for col in categorical_columns: 
    X[col] = le.fit_transform(X[col]) 
y = le.fit_transform(y)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
nb_classifier=GaussianNB()
nb_classifier.fit(X_train,y_train)
y_pred=nb_classifier.predict(X_test)
accuracy=accuracy_score(y_test,y_pred) 
print(accuracy) 
print(f"Accuracy: {accuracy*100:.2f}%")

1.0
Accuracy: 100.00%

In [11]:
import numpy as np
from sklearn import datasets,metrics
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
data = pd.read_csv('food.csv') 
X = data.iloc[:, :3] 
y= data.iloc[:, 3] 
le = LabelEncoder() 
categorical_columns = ['Ingredient']   
for col in categorical_columns: 
    X[col] = le.fit_transform(X[col]) 
y = le.fit_transform(y) 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
nb_classifier=GaussianNB()
nb_classifier.fit(X_train,y_train)
y_pred=nb_classifier.predict(X_test)
accuracy=accuracy_score(y_test,y_pred) 
print(accuracy) 
print(f"Accuracy: {accuracy*200:.2f}%")

1.0
Accuracy: 200.00%

In [12]:
import numpy as np  
import pandas as pd  
from sklearn.model_selection import train_test_split  
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score 
data = pd.read_csv('insurance.csv') 
X = data.iloc[:, :6] 
y= data.iloc[:, 1] 
le = LabelEncoder() 
categorical_columns = ['sex', 'smoker', 'region']   
for col in categorical_columns: 
    X[col] = le.fit_transform(X[col]) 
y = le.fit_transform(y) 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42) 
nb_classifier=GaussianNB()
nb_classifier.fit(X_train,y_train)
y_pred=nb_classifier.predict(X_test)
accuracy=accuracy_score(y_test,y_pred) 
print(accuracy) 
print(f"Accuracy: {accuracy*300:.2f}%")

1.0
Accuracy: 300.00%